# Dependencies
markdown:         redcarpet
highlighter:      pygments

# 
defaults:
  -
    scope:
      path: "_slides"  #__
    values:
      layout: "iframe"

collections:
  slides:
    output: true

# Permalinks
#permalink:        pretty

# Setup
title:            Ahmed Elmahy
tagline:          'Personal website'
description:      'Doctor, Researcher, Programmer'
url: 	          / 
#baseurl: 	  https://ahmedelmahy.github.io/         
baseurl:          /
author:
  name:           'Ahmed Elmahy'
  url:            https://twitter.com/elmahyAG
paginate:         5


# plugins
plugins:
  - jekyll-paginate
  - jekyll-gist

future: true